var data = [
  {
    "title": "Twin Falls Idaho",
    "genre": "드라마",
    "type": "현대소설",
    "origin": "없음",
    "era": "90년대",
    "rating": "전체관람가",
    "cost": 5,
    "profit_America": 9,
    "profit_world": 10,
    "rotten_tomato": 77,
    "IMDB_score": 7.1,
    "IMDB_number": 2810
  },
  {
    "title": "Beverly Hills Cop II",
    "genre": "액션",
    "type": "현대소설",
    "origin": "없음",
    "era": "80년대",
    "rating": "전체관람가",
    "cost": 200,
    "profit_America": 1536,
    "profit_world": 2766,
    "rotten_tomato": 46,
    "IMDB_score": 6.1,
    "IMDB_number": 29712
  },
  {
    "title": "Broken Arrow",
    "genre": "액션",
    "type": "현대소설",
    "origin": "없음",
    "era": "90년대",
    "rating": "전체관람가",
    "cost": 650,
    "profit_America": 706,
    "profit_world": 1483,
    "rotten_tomato": 55,
    "IMDB_score": 5.8,
    "IMDB_number": 33584
  },
  {
    "title": "Batman",
    "genre": "액션",
    "type": "영웅물",
    "origin": "만화",
    "era": "80년대",
    "rating": "15세이상",
    "cost": 350,
    "profit_America": 2511,
    "profit_world": 4113,
    "rotten_tomato": 71,
    "IMDB_score": 7.6,
    "IMDB_number": 111464
  },
  {
    "title": "Copycat",
    "genre": "스릴러",
    "type": "현대소설",
    "origin": "없음",
    "era": "90년대",
    "rating": "전체관람가",
    "cost": 200,
    "profit_America": 320,
    "profit_world": 320,
    "rotten_tomato": 75,
    "IMDB_score": 6.5,
    "IMDB_number": 17182
  },
  {
    "title": "Ed Wood",
    "genre": "코미디",
    "type": "각색",
    "origin": "책",
    "era": "90년대",
    "rating": "전체관람가",
    "cost": 180,
    "profit_America": 58,
    "profit_world": 58,
    "rotten_tomato": 91,
    "IMDB_score": 8.1,
    "IMDB_number": 74171
  },
  {
    "title": "From Dusk Till Dawn",
    "genre": "호러",
    "type": "판타지",
    "origin": "없음",
    "era": "90년대",
    "rating": "전체관람가",
    "cost": 200,
    "profit_America": 257,
    "profit_world": 257,
    "rotten_tomato": 63,
    "IMDB_score": 7.1,
    "IMDB_number": 80234
  },
  {
    "title": "The First Wives Club",
    "genre": "코미디",
    "type": "현대소설",
    "origin": "책",
    "era": "90년대",
    "rating": "7세이상",
    "cost": 300,
    "profit_America": 1054,
    "profit_world": 1814,
    "rotten_tomato": 41,
    "IMDB_score": 5.6,
    "IMDB_number": 14682
  },
  {
    "title": "Home Alone 2: Lost in New York",
    "genre": "코미디",
    "type": "현대소설",
    "origin": "없음",
    "era": "90년대",
    "rating": "7세이상",
    "cost": 200,
    "profit_America": 1735,
    "profit_world": 3589,
    "rotten_tomato": 21,
    "IMDB_score": 5.8,
    "IMDB_number": 51408
  },
  {
    "title": "Home Alone",
    "genre": "코미디",
    "type": "현대소설",
    "origin": "없음",
    "era": "90년대",
    "rating": "7세이상",
    "cost": 150,
    "profit_America": 2857,
    "profit_world": 4766,
    "rotten_tomato": 47,
    "IMDB_score": 7,
    "IMDB_number": 79080
  },
  {
    "title": "Jack",
    "genre": "드라마",
    "type": "현대소설",
    "origin": "없음",
    "era": "90년대",
    "rating": "15세이상",
    "cost": 450,
    "profit_America": 586,
    "profit_world": 586,
    "rotten_tomato": 17,
    "IMDB_score": 5.3,
    "IMDB_number": 17267
  },
  {
    "title": "JFK",
    "genre": "드라마",
    "type": "각색",
    "origin": "책",
    "era": "90년대",
    "rating": "전체관람가",
    "cost": 400,
    "profit_America": 704,
    "profit_world": 2054,
    "rotten_tomato": 83,
    "IMDB_score": 8,
    "IMDB_number": 59684
  },
  {
    "title": "Jumanji",
    "genre": "어드벤처",
    "type": "판타지",
    "origin": "책",
    "era": "90년대",
    "rating": "7세이상",
    "cost": 650,
    "profit_America": 1004,
    "profit_world": 2627,
    "rotten_tomato": 48,
    "IMDB_score": 6.4,
    "IMDB_number": 54973
  },
  {
    "title": "Kiss of Death",
    "genre": "드라마",
    "type": "현대소설",
    "origin": "영화",
    "era": "90년대",
    "rating": "전체관람가",
    "cost": 400,
    "profit_America": 149,
    "profit_world": 149,
    "rotten_tomato": 67,
    "IMDB_score": 7.6,
    "IMDB_number": 2374
  },
  {
    "title": "Alien³",
    "genre": "액션",
    "type": "공상과학",
    "origin": "없음",
    "era": "90년대",
    "rating": "전체관람가",
    "cost": 550,
    "profit_America": 549,
    "profit_world": 1585,
    "rotten_tomato": 37,
    "IMDB_score": 6.3,
    "IMDB_number": 78860
  },
  {
    "title": "Lone Star",
    "genre": "드라마",
    "type": "현대소설",
    "origin": "없음",
    "era": "90년대",
    "rating": "전체관람가",
    "cost": 50,
    "profit_America": 129,
    "profit_world": 129,
    "rotten_tomato": 92,
    "IMDB_score": 7.6,
    "IMDB_number": 14599
  },
  {
    "title": "Menace II Society",
    "genre": "액션",
    "type": "현대소설",
    "origin": "없음",
    "era": "90년대",
    "rating": "전체관람가",
    "cost": 35,
    "profit_America": 277,
    "profit_world": 277,
    "rotten_tomato": 85,
    "IMDB_score": 7.4,
    "IMDB_number": 14807
  },
  {
    "title": "Mary Reilly",
    "genre": "드라마",
    "type": "역사소설",
    "origin": "책",
    "era": "90년대",
    "rating": "전체관람가",
    "cost": 470,
    "profit_America": 57,
    "profit_world": 63,
    "rotten_tomato": 27,
    "IMDB_score": 5.5,
    "IMDB_number": 6864
  },
  {
    "title": "The Mighty Ducks",
    "genre": "코미디",
    "type": "현대소설",
    "origin": "없음",
    "era": "90년대",
    "rating": "7세이상",
    "cost": 100,
    "profit_America": 507,
    "profit_world": 507,
    "rotten_tomato": 8,
    "IMDB_score": 5.9,
    "IMDB_number": 15479
  },
  {
    "title": "The English Patient",
    "genre": "드라마",
    "type": "역사소설",
    "origin": "책",
    "era": "90년대",
    "rating": "전체관람가",
    "cost": 350,
    "profit_America": 787,
    "profit_world": 2317,
    "rotten_tomato": 83,
    "IMDB_score": 7.3,
    "IMDB_number": 54484
  },
  {
    "title": "Outbreak",
    "genre": "스릴러",
    "type": "현대소설",
    "origin": "없음",
    "era": "90년대",
    "rating": "전체관람가",
    "cost": 500,
    "profit_America": 678,
    "profit_world": 678,
    "rotten_tomato": 59,
    "IMDB_score": 6.4,
    "IMDB_number": 33192
  },
  {
    "title": "The Phantom",
    "genre": "액션",
    "type": "영웅물",
    "origin": "만화",
    "era": "90년대",
    "rating": "7세이상",
    "cost": 450,
    "profit_America": 172,
    "profit_world": 172,
    "rotten_tomato": 43,
    "IMDB_score": 4.8,
    "IMDB_number": 9477
  },
  {
    "title": "The Scarlet Letter",
    "genre": "드라마",
    "type": "역사소설",
    "origin": "책",
    "era": "90년대",
    "rating": "전체관람가",
    "cost": 500,
    "profit_America": 103,
    "profit_world": 103,
    "rotten_tomato": 15,
    "IMDB_score": 4.6,
    "IMDB_number": 6155
  },
  {
    "title": "The Usual Suspects",
    "genre": "드라마",
    "type": "현대소설",
    "origin": "없음",
    "era": "90년대",
    "rating": "전체관람가",
    "cost": 60,
    "profit_America": 233,
    "profit_world": 233,
    "rotten_tomato": 87,
    "IMDB_score": 8.7,
    "IMDB_number": 266890
  },
  {
    "title": "Serial Mom",
    "genre": "코미디",
    "type": "현대소설",
    "origin": "없음",
    "era": "90년대",
    "rating": "전체관람가",
    "cost": 130,
    "profit_America": 78,
    "profit_world": 78,
    "rotten_tomato": 61,
    "IMDB_score": 6.4,
    "IMDB_number": 10999
  },
  {
    "title": "Speed",
    "genre": "액션",
    "type": "현대소설",
    "origin": "없음",
    "era": "90년대",
    "rating": "전체관람가",
    "cost": 300,
    "profit_America": 1212,
    "profit_world": 2832,
    "rotten_tomato": 90,
    "IMDB_score": 2.6,
    "IMDB_number": 4175
  },
  {
    "title": "The Fan",
    "genre": "스릴러",
    "type": "현대소설",
    "origin": "책",
    "era": "90년대",
    "rating": "전체관람가",
    "cost": 550,
    "profit_America": 185,
    "profit_world": 185,
    "rotten_tomato": 40,
    "IMDB_score": 5.6,
    "IMDB_number": 20640
  },
  {
    "title": "Trainspotting",
    "genre": "드라마",
    "type": "현대소설",
    "origin": "책",
    "era": "90년대",
    "rating": "전체관람가",
    "cost": 31,
    "profit_America": 165,
    "profit_world": 240,
    "rotten_tomato": 89,
    "IMDB_score": 8.2,
    "IMDB_number": 150483
  },
  {
    "title": "Toy Story",
    "genre": "어드벤처",
    "type": "아동소설",
    "origin": "없음",
    "era": "90년대",
    "rating": "19세이상",
    "cost": 300,
    "profit_America": 1917,
    "profit_world": 3619,
    "rotten_tomato": 100,
    "IMDB_score": 8.2,
    "IMDB_number": 151143
  },
  {
    "title": "Vampire in Brooklyn",
    "genre": "호러",
    "type": "판타지",
    "origin": "없음",
    "era": "90년대",
    "rating": "전체관람가",
    "cost": 140,
    "profit_America": 196,
    "profit_world": 196,
    "rotten_tomato": 11,
    "IMDB_score": 4.3,
    "IMDB_number": 8200
  },
  {
    "title": "A Walk on the Moon",
    "genre": "드라마",
    "type": "역사소설",
    "origin": "없음",
    "era": "90년대",
    "rating": "전체관람가",
    "cost": 140,
    "profit_America": 47,
    "profit_world": 47,
    "rotten_tomato": 74,
    "IMDB_score": 6.4,
    "IMDB_number": 4125
  },
  {
    "title": "Warriors of Virtue",
    "genre": "액션",
    "type": "현대소설",
    "origin": "없음",
    "era": "90년대",
    "rating": "7세이상",
    "cost": 350,
    "profit_America": 64,
    "profit_world": 64,
    "rotten_tomato": 10,
    "IMDB_score": 4,
    "IMDB_number": 1202
  },
  {
    "title": "102 Dalmatians",
    "genre": "코미디",
    "type": "아동소설",
    "origin": "책",
    "era": "2000년대",
    "rating": "19세이상",
    "cost": 850,
    "profit_America": 669,
    "profit_world": 669,
    "rotten_tomato": 30,
    "IMDB_score": 4.4,
    "IMDB_number": 7147
  },
  {
    "title": "16 Blocks",
    "genre": "액션",
    "type": "현대소설",
    "origin": "없음",
    "era": "2000년대",
    "rating": "15세이상",
    "cost": 450,
    "profit_America": 368,
    "profit_world": 655,
    "rotten_tomato": 55,
    "IMDB_score": 6.7,
    "IMDB_number": 41207
  },
  {
    "title": "88 Minutes",
    "genre": "스릴러",
    "type": "현대소설",
    "origin": "없음",
    "era": "2000년대",
    "rating": "전체관람가",
    "cost": 300,
    "profit_America": 169,
    "profit_world": 329,
    "rotten_tomato": 5,
    "IMDB_score": 5.9,
    "IMDB_number": 31205
  },
  {
    "title": "Eight Below",
    "genre": "어드벤처",
    "type": "현대소설",
    "origin": "영화",
    "era": "2000년대",
    "rating": "7세이상",
    "cost": 400,
    "profit_America": 816,
    "profit_world": 1206,
    "rotten_tomato": 71,
    "IMDB_score": 7.3,
    "IMDB_number": 17717
  },
  {
    "title": "8 Mile",
    "genre": "드라마",
    "type": "현대소설",
    "origin": "없음",
    "era": "2000년대",
    "rating": "전체관람가",
    "cost": 410,
    "profit_America": 1167,
    "profit_world": 2429,
    "rotten_tomato": 74,
    "IMDB_score": 6.7,
    "IMDB_number": 55877
  },
  {
    "title": "A Bug's Life",
    "genre": "어드벤처",
    "type": "판타지",
    "origin": "없음",
    "era": "90년대",
    "rating": "19세이상",
    "cost": 450,
    "profit_America": 1627,
    "profit_world": 3631,
    "rotten_tomato": 91,
    "IMDB_score": 7.3,
    "IMDB_number": 56866
  },
  {
    "title": "Absolute Power",
    "genre": "스릴러",
    "type": "현대소설",
    "origin": "책",
    "era": "90년대",
    "rating": "전체관람가",
    "cost": 500,
    "profit_America": 500,
    "profit_world": 500,
    "rotten_tomato": 46,
    "IMDB_score": 6.5,
    "IMDB_number": 20154
  },
  {
    "title": "All the King's Men",
    "genre": "드라마",
    "type": "역사소설",
    "origin": "책",
    "era": "2000년대",
    "rating": "15세이상",
    "cost": 550,
    "profit_America": 72,
    "profit_world": 95,
    "rotten_tomato": 11,
    "IMDB_score": 6,
    "IMDB_number": 11994
  },
  {
    "title": "Alfie",
    "genre": "코미디",
    "type": "현대소설",
    "origin": "영화",
    "era": "2000년대",
    "rating": "전체관람가",
    "cost": 400,
    "profit_America": 133,
    "profit_world": 351,
    "rotten_tomato": 49,
    "IMDB_score": 6.1,
    "IMDB_number": 20769
  },
  {
    "title": "Alien",
    "genre": "호러",
    "type": "공상과학",
    "origin": "없음",
    "era": "80년대 이전",
    "rating": "전체관람가",
    "cost": 90,
    "profit_America": 809,
    "profit_world": 2036,
    "rotten_tomato": 97,
    "IMDB_score": 8.5,
    "IMDB_number": 180387
  },
  {
    "title": "Almost Famous",
    "genre": "코미디",
    "type": "각색",
    "origin": "없음",
    "era": "2000년대",
    "rating": "전체관람가",
    "cost": 600,
    "profit_America": 325,
    "profit_world": 473,
    "rotten_tomato": 88,
    "IMDB_score": 8,
    "IMDB_number": 94424
  },
  {
    "title": "Bruce Almighty",
    "genre": "코미디",
    "type": "판타지",
    "origin": "없음",
    "era": "2000년대",
    "rating": "15세이상",
    "cost": 810,
    "profit_America": 2427,
    "profit_world": 4850,
    "rotten_tomato": 48,
    "IMDB_score": 6.6,
    "IMDB_number": 92494
  },
  {
    "title": "Angels & Demons",
    "genre": "스릴러",
    "type": "현대소설",
    "origin": "책",
    "era": "2000년대",
    "rating": "15세이상",
    "cost": 1500,
    "profit_America": 1333,
    "profit_world": 4859,
    "rotten_tomato": 35,
    "IMDB_score": 6.7,
    "IMDB_number": 60114
  },
  {
    "title": "The Animal",
    "genre": "코미디",
    "type": "현대소설",
    "origin": "없음",
    "era": "2000년대",
    "rating": "15세이상",
    "cost": 220,
    "profit_America": 557,
    "profit_world": 557,
    "rotten_tomato": 30,
    "IMDB_score": 4.6,
    "IMDB_number": 18601
  },
  {
    "title": "Anna and the King",
    "genre": "드라마",
    "type": "각색",
    "origin": "책",
    "era": "90년대",
    "rating": "15세이상",
    "cost": 750,
    "profit_America": 392,
    "profit_world": 392,
    "rotten_tomato": 51,
    "IMDB_score": 6.5,
    "IMDB_number": 14881
  },
  {
    "title": "Australia",
    "genre": "드라마",
    "type": "역사소설",
    "origin": "없음",
    "era": "2000년대",
    "rating": "15세이상",
    "cost": 780,
    "profit_America": 495,
    "profit_world": 2074,
    "rotten_tomato": 54,
    "IMDB_score": 6.8,
    "IMDB_number": 38089
  },
  {
    "title": "Away We Go",
    "genre": "코미디",
    "type": "현대소설",
    "origin": "없음",
    "era": "2000년대",
    "rating": "전체관람가",
    "cost": 210,
    "profit_America": 94,
    "profit_world": 101,
    "rotten_tomato": 66,
    "IMDB_score": 7.3,
    "IMDB_number": 14929
  },
  {
    "title": "Baby Boy",
    "genre": "드라마",
    "type": "현대소설",
    "origin": "없음",
    "era": "2000년대",
    "rating": "전체관람가",
    "cost": 160,
    "profit_America": 287,
    "profit_world": 287,
    "rotten_tomato": 69,
    "IMDB_score": 6.1,
    "IMDB_number": 4485
  },
  {
    "title": "Body of Lies",
    "genre": "스릴러",
    "type": "현대소설",
    "origin": "책",
    "era": "2000년대",
    "rating": "전체관람가",
    "cost": 675,
    "profit_America": 393,
    "profit_world": 1083,
    "rotten_tomato": 52,
    "IMDB_score": 7.2,
    "IMDB_number": 53921
  },
  {
    "title": "Bee Movie",
    "genre": "코미디",
    "type": "아동소설",
    "origin": "없음",
    "era": "2000년대",
    "rating": "7세이상",
    "cost": 1500,
    "profit_America": 1266,
    "profit_world": 2875,
    "rotten_tomato": 51,
    "IMDB_score": 6.3,
    "IMDB_number": 30575
  },
  {
    "title": "Beloved",
    "genre": "드라마",
    "type": "역사소설",
    "origin": "책",
    "era": "90년대",
    "rating": "전체관람가",
    "cost": 530,
    "profit_America": 228,
    "profit_world": 228,
    "rotten_tomato": 77,
    "IMDB_score": 5.3,
    "IMDB_number": 102
  },
  {
    "title": "Big Fat Liar",
    "genre": "코미디",
    "type": "현대소설",
    "origin": "없음",
    "era": "2000년대",
    "rating": "7세이상",
    "cost": 150,
    "profit_America": 478,
    "profit_world": 523,
    "rotten_tomato": 43,
    "IMDB_score": 5.2,
    "IMDB_number": 9877
  },
  {
    "title": "Blood Work",
    "genre": "스릴러",
    "type": "현대소설",
    "origin": "책",
    "era": "2000년대",
    "rating": "전체관람가",
    "cost": 500,
    "profit_America": 261,
    "profit_world": 261,
    "rotten_tomato": 54,
    "IMDB_score": 6.3,
    "IMDB_number": 16751
  },
  {
    "title": "Bandits",
    "genre": "코미디",
    "type": "현대소설",
    "origin": "없음",
    "era": "2000년대",
    "rating": "15세이상",
    "cost": 750,
    "profit_America": 415,
    "profit_world": 715,
    "rotten_tomato": 63,
    "IMDB_score": 6.5,
    "IMDB_number": 30732
  },
  {
    "title": "Boys Don't Cry",
    "genre": "드라마",
    "type": "각색",
    "origin": "없음",
    "era": "90년대",
    "rating": "전체관람가",
    "cost": 20,
    "profit_America": 115,
    "profit_world": 207,
    "rotten_tomato": 88,
    "IMDB_score": 7.6,
    "IMDB_number": 34435
  },
  {
    "title": "Barbershop",
    "genre": "코미디",
    "type": "현대소설",
    "origin": "없음",
    "era": "2000년대",
    "rating": "15세이상",
    "cost": 120,
    "profit_America": 757,
    "profit_world": 770,
    "rotten_tomato": 82,
    "IMDB_score": 6.2,
    "IMDB_number": 11164
  },
  {
    "title": "Bulworth",
    "genre": "코미디",
    "type": "현대소설",
    "origin": "없음",
    "era": "90년대",
    "rating": "전체관람가",
    "cost": 300,
    "profit_America": 265,
    "profit_world": 292,
    "rotten_tomato": 75,
    "IMDB_score": 6.8,
    "IMDB_number": 15486
  },
  {
    "title": "Bowfinger",
    "genre": "코미디",
    "type": "현대소설",
    "origin": "없음",
    "era": "90년대",
    "rating": "15세이상",
    "cost": 550,
    "profit_America": 664,
    "profit_world": 986,
    "rotten_tomato": 79,
    "IMDB_score": 6.4,
    "IMDB_number": 33389
  },
  {
    "title": "Cars",
    "genre": "코미디",
    "type": "아동소설",
    "origin": "없음",
    "era": "2000년대",
    "rating": "19세이상",
    "cost": 700,
    "profit_America": 2440,
    "profit_world": 4619,
    "rotten_tomato": 74,
    "IMDB_score": 7.5,
    "IMDB_number": 66809
  },
  {
    "title": "Catch Me if You Can",
    "genre": "드라마",
    "type": "각색",
    "origin": "책",
    "era": "2000년대",
    "rating": "15세이상",
    "cost": 520,
    "profit_America": 1646,
    "profit_world": 3511,
    "rotten_tomato": 96,
    "IMDB_score": 5.7,
    "IMDB_number": 224
  },
  {
    "title": "Crocodile Dundee in Los Angeles",
    "genre": "어드벤처",
    "type": "현대소설",
    "origin": "없음",
    "era": "2000년대",
    "rating": "7세이상",
    "cost": 250,
    "profit_America": 255,
    "profit_world": 393,
    "rotten_tomato": 12,
    "IMDB_score": 4.6,
    "IMDB_number": 7082
  },
  {
    "title": "Chicken Little",
    "genre": "어드벤처",
    "type": "아동소설",
    "origin": "없음",
    "era": "2000년대",
    "rating": "19세이상",
    "cost": 600,
    "profit_America": 1353,
    "profit_world": 3144,
    "rotten_tomato": 36,
    "IMDB_score": 5.8,
    "IMDB_number": 17415
  },
  {
    "title": "Bride of Chucky",
    "genre": "호러",
    "type": "판타지",
    "origin": "없음",
    "era": "90년대",
    "rating": "전체관람가",
    "cost": 250,
    "profit_America": 324,
    "profit_world": 506,
    "rotten_tomato": 43,
    "IMDB_score": 5.3,
    "IMDB_number": 13735
  },
  {
    "title": "Children of Men",
    "genre": "스릴러",
    "type": "공상과학",
    "origin": "책",
    "era": "2000년대",
    "rating": "전체관람가",
    "cost": 760,
    "profit_America": 355,
    "profit_world": 694,
    "rotten_tomato": 93,
    "IMDB_score": 8.1,
    "IMDB_number": 158125
  },
  {
    "title": "Charlotte's Web",
    "genre": "드라마",
    "type": "판타지",
    "origin": "책",
    "era": "2000년대",
    "rating": "19세이상",
    "cost": 825,
    "profit_America": 829,
    "profit_world": 1439,
    "rotten_tomato": 78,
    "IMDB_score": 6.7,
    "IMDB_number": 8028
  },
  {
    "title": "The Contender",
    "genre": "드라마",
    "type": "현대소설",
    "origin": "없음",
    "era": "2000년대",
    "rating": "전체관람가",
    "cost": 90,
    "profit_America": 178,
    "profit_world": 178,
    "rotten_tomato": 76,
    "IMDB_score": 6.9,
    "IMDB_number": 13709
  },
  {
    "title": "Confessions of a Dangerous Mind",
    "genre": "드라마",
    "type": "각색",
    "origin": "책",
    "era": "2000년대",
    "rating": "전체관람가",
    "cost": 290,
    "profit_America": 160,
    "profit_world": 330,
    "rotten_tomato": 79,
    "IMDB_score": 7.1,
    "IMDB_number": 36258
  },
  {
    "title": "Come Early Morning",
    "genre": "드라마",
    "type": "현대소설",
    "origin": "없음",
    "era": "2000년대",
    "rating": "전체관람가",
    "cost": 60,
    "profit_America": 1,
    "profit_world": 1,
    "rotten_tomato": 83,
    "IMDB_score": 6.2,
    "IMDB_number": 1511
  },
  {
    "title": "Contact",
    "genre": "드라마",
    "type": "공상과학",
    "origin": "책",
    "era": "90년대",
    "rating": "7세이상",
    "cost": 900,
    "profit_America": 1009,
    "profit_world": 1659,
    "rotten_tomato": 67,
    "IMDB_score": 7.3,
    "IMDB_number": 73684
  },
  {
    "title": "Crash",
    "genre": "드라마",
    "type": "현대소설",
    "origin": "없음",
    "era": "2000년대",
    "rating": "전체관람가",
    "cost": 65,
    "profit_America": 545,
    "profit_world": 983,
    "rotten_tomato": 75,
    "IMDB_score": 6.1,
    "IMDB_number": 20886
  },
  {
    "title": "Cruel Intentions",
    "genre": "드라마",
    "type": "현대소설",
    "origin": "책",
    "era": "90년대",
    "rating": "전체관람가",
    "cost": 110,
    "profit_America": 382,
    "profit_world": 758,
    "rotten_tomato": 47,
    "IMDB_score": 6.7,
    "IMDB_number": 66861
  },
  {
    "title": "Clockstoppers",
    "genre": "어드벤처",
    "type": "공상과학",
    "origin": "없음",
    "era": "2000년대",
    "rating": "7세이상",
    "cost": 260,
    "profit_America": 369,
    "profit_world": 387,
    "rotten_tomato": 28,
    "IMDB_score": 5,
    "IMDB_number": 6392
  },
  {
    "title": "Daredevil",
    "genre": "액션",
    "type": "영웅물",
    "origin": "만화",
    "era": "2000년대",
    "rating": "15세이상",
    "cost": 800,
    "profit_America": 1025,
    "profit_world": 1791,
    "rotten_tomato": 44,
    "IMDB_score": 5.5,
    "IMDB_number": 63574
  },
  {
    "title": "Donnie Darko",
    "genre": "드라마",
    "type": "판타지",
    "origin": "없음",
    "era": "2000년대",
    "rating": "전체관람가",
    "cost": 45,
    "profit_America": 12,
    "profit_world": 41,
    "rotten_tomato": 84,
    "IMDB_score": 8.3,
    "IMDB_number": 210713
  },
  {
    "title": "Date Movie",
    "genre": "코미디",
    "type": "현대소설",
    "origin": "없음",
    "era": "2000년대",
    "rating": "15세이상",
    "cost": 200,
    "profit_America": 485,
    "profit_world": 845,
    "rotten_tomato": 6,
    "IMDB_score": 2.6,
    "IMDB_number": 31821
  },
  {
    "title": "Double Jeopardy",
    "genre": "액션",
    "type": "현대소설",
    "origin": "없음",
    "era": "90년대",
    "rating": "전체관람가",
    "cost": 400,
    "profit_America": 1167,
    "profit_world": 1778,
    "rotten_tomato": 25,
    "IMDB_score": 6,
    "IMDB_number": 28887
  },
  {
    "title": "The Departed",
    "genre": "드라마",
    "type": "현대소설",
    "origin": "영화",
    "era": "2000년대",
    "rating": "전체관람가",
    "cost": 900,
    "profit_America": 1333,
    "profit_world": 2905,
    "rotten_tomato": 93,
    "IMDB_score": 8.5,
    "IMDB_number": 264148
  },
  {
    "title": "Drag Me To Hell",
    "genre": "호러",
    "type": "판타지",
    "origin": "없음",
    "era": "2000년대",
    "rating": "15세이상",
    "cost": 300,
    "profit_America": 421,
    "profit_world": 857,
    "rotten_tomato": 92,
    "IMDB_score": 7.1,
    "IMDB_number": 51343
  },
  {
    "title": "Disturbia",
    "genre": "스릴러",
    "type": "현대소설",
    "origin": "없음",
    "era": "2000년대",
    "rating": "15세이상",
    "cost": 200,
    "profit_America": 802,
    "profit_world": 1175,
    "rotten_tomato": 68,
    "IMDB_score": 7,
    "IMDB_number": 72231
  },
  {
    "title": "Death at a Funeral",
    "genre": "코미디",
    "type": "현대소설",
    "origin": "없음",
    "era": "2000년대",
    "rating": "전체관람가",
    "cost": 200,
    "profit_America": 85,
    "profit_world": 347,
    "rotten_tomato": 61,
    "IMDB_score": 5.1,
    "IMDB_number": 6628
  },
  {
    "title": "The Da Vinci Code",
    "genre": "스릴러",
    "type": "현대소설",
    "origin": "책",
    "era": "2000년대",
    "rating": "15세이상",
    "cost": 1250,
    "profit_America": 2175,
    "profit_world": 7572,
    "rotten_tomato": 25,
    "IMDB_score": 6.4,
    "IMDB_number": 116903
  },
  {
    "title": "Eagle Eye",
    "genre": "스릴러",
    "type": "현대소설",
    "origin": "없음",
    "era": "2000년대",
    "rating": "15세이상",
    "cost": 800,
    "profit_America": 1014,
    "profit_world": 1780,
    "rotten_tomato": 27,
    "IMDB_score": 6.6,
    "IMDB_number": 52336
  },
  {
    "title": "8MM",
    "genre": "스릴러",
    "type": "현대소설",
    "origin": "없음",
    "era": "90년대",
    "rating": "전체관람가",
    "cost": 400,
    "profit_America": 364,
    "profit_world": 963,
    "rotten_tomato": 22,
    "IMDB_score": 6.3,
    "IMDB_number": 47753
  },
  {
    "title": "The End of the Affair",
    "genre": "드라마",
    "type": "역사소설",
    "origin": "책",
    "era": "90년대",
    "rating": "전체관람가",
    "cost": 230,
    "profit_America": 106,
    "profit_world": 106,
    "rotten_tomato": 67,
    "IMDB_score": 6.9,
    "IMDB_number": 9969
  },
  {
    "title": "Entrapment",
    "genre": "스릴러",
    "type": "현대소설",
    "origin": "없음",
    "era": "90년대",
    "rating": "15세이상",
    "cost": 660,
    "profit_America": 877,
    "profit_world": 2117,
    "rotten_tomato": 38,
    "IMDB_score": 6.1,
    "IMDB_number": 40764
  },
  {
    "title": "Enough",
    "genre": "스릴러",
    "type": "현대소설",
    "origin": "없음",
    "era": "2000년대",
    "rating": "15세이상",
    "cost": 380,
    "profit_America": 391,
    "profit_world": 391,
    "rotten_tomato": 21,
    "IMDB_score": 6.5,
    "IMDB_number": 92
  },
  {
    "title": "Epic Movie",
    "genre": "코미디",
    "type": "현대소설",
    "origin": "없음",
    "era": "2000년대",
    "rating": "15세이상",
    "cost": 200,
    "profit_America": 397,
    "profit_world": 868,
    "rotten_tomato": 2,
    "IMDB_score": 2.2,
    "IMDB_number": 48975
  },
  {
    "title": "Event Horizon",
    "genre": "호러",
    "type": "공상과학",
    "origin": "없음",
    "era": "90년대",
    "rating": "전체관람가",
    "cost": 600,
    "profit_America": 266,
    "profit_world": 266,
    "rotten_tomato": 21,
    "IMDB_score": 6.3,
    "IMDB_number": 44671
  },
  {
    "title": "Extreme Ops",
    "genre": "액션",
    "type": "현대소설",
    "origin": "없음",
    "era": "2000년대",
    "rating": "15세이상",
    "cost": 400,
    "profit_America": 48,
    "profit_world": 126,
    "rotten_tomato": 6,
    "IMDB_score": 4.1,
    "IMDB_number": 3195
  },
  {
    "title": "Far From Heaven",
    "genre": "드라마",
    "type": "역사소설",
    "origin": "없음",
    "era": "2000년대",
    "rating": "15세이상",
    "cost": 135,
    "profit_America": 159,
    "profit_world": 290,
    "rotten_tomato": 89,
    "IMDB_score": 7.5,
    "IMDB_number": 20239
  },
  {
    "title": "Facing the Giants",
    "genre": "드라마",
    "type": "현대소설",
    "origin": "없음",
    "era": "2000년대",
    "rating": "7세이상",
    "cost": 1,
    "profit_America": 101,
    "profit_world": 101,
    "rotten_tomato": 9,
    "IMDB_score": 6,
    "IMDB_number": 4901
  },
  {
    "title": "Final Destination 3",
    "genre": "호러",
    "type": "판타지",
    "origin": "없음",
    "era": "2000년대",
    "rating": "전체관람가",
    "cost": 250,
    "profit_America": 540,
    "profit_world": 1127,
    "rotten_tomato": 45,
    "IMDB_score": 5.9,
    "IMDB_number": 32263
  },
  {
    "title": "The Final Destination",
    "genre": "호러",
    "type": "판타지",
    "origin": "없음",
    "era": "2000년대",
    "rating": "전체관람가",
    "cost": 400,
    "profit_America": 664,
    "profit_world": 1857,
    "rotten_tomato": 27,
    "IMDB_score": 4.9,
    "IMDB_number": 20319
  },
  {
    "title": "From Hell",
    "genre": "스릴러",
    "type": "역사소설",
    "origin": "만화",
    "era": "2000년대",
    "rating": "전체관람가",
    "cost": 350,
    "profit_America": 315,
    "profit_world": 315,
    "rotten_tomato": 57,
    "IMDB_score": 6.8,
    "IMDB_number": 53477
  },
  {
    "title": "Fight Club",
    "genre": "드라마",
    "type": "현대소설",
    "origin": "책",
    "era": "90년대",
    "rating": "전체관람가",
    "cost": 650,
    "profit_America": 370,
    "profit_world": 1008,
    "rotten_tomato": 81,
    "IMDB_score": 8.8,
    "IMDB_number": 382470
  },
  {
    "title": "Finding Forrester",
    "genre": "드라마",
    "type": "현대소설",
    "origin": "없음",
    "era": "2000년대",
    "rating": "15세이상",
    "cost": 430,
    "profit_America": 517,
    "profit_world": 800,
    "rotten_tomato": 74,
    "IMDB_score": 7.2,
    "IMDB_number": 35966
  },
  {
    "title": "Flubber",
    "genre": "코미디",
    "type": "아동소설",
    "origin": "영화",
    "era": "90년대",
    "rating": "7세이상",
    "cost": 800,
    "profit_America": 929,
    "profit_world": 1779,
    "rotten_tomato": 17,
    "IMDB_score": 4.6,
    "IMDB_number": 18890
  },
  {
    "title": "Flushed Away",
    "genre": "코미디",
    "type": "아동소설",
    "origin": "없음",
    "era": "2000년대",
    "rating": "7세이상",
    "cost": 1490,
    "profit_America": 646,
    "profit_world": 1776,
    "rotten_tomato": 72,
    "IMDB_score": 7,
    "IMDB_number": 21334
  },
  {
    "title": "Friday Night Lights",
    "genre": "드라마",
    "type": "현대소설",
    "origin": "책",
    "era": "2000년대",
    "rating": "15세이상",
    "cost": 300,
    "profit_America": 612,
    "profit_world": 619,
    "rotten_tomato": 81,
    "IMDB_score": 7.2,
    "IMDB_number": 20868
  },
  {
    "title": "The Princess and the Frog",
    "genre": "어드벤처",
    "type": "아동소설",
    "origin": "책",
    "era": "2000년대",
    "rating": "19세이상",
    "cost": 1050,
    "profit_America": 1043,
    "profit_world": 2634,
    "rotten_tomato": 84,
    "IMDB_score": 7.4,
    "IMDB_number": 16232
  },
  {
    "title": "Fireproof",
    "genre": "드라마",
    "type": "현대소설",
    "origin": "없음",
    "era": "2000년대",
    "rating": "7세이상",
    "cost": 5,
    "profit_America": 334,
    "profit_world": 334,
    "rotten_tomato": 40,
    "IMDB_score": 5.6,
    "IMDB_number": 5498
  },
  {
    "title": "For Your Consideration",
    "genre": "코미디",
    "type": "현대소설",
    "origin": "없음",
    "era": "2000년대",
    "rating": "15세이상",
    "cost": 120,
    "profit_America": 55,
    "profit_world": 55,
    "rotten_tomato": 50,
    "IMDB_score": 6.2,
    "IMDB_number": 7780
  },
  {
    "title": "The Game",
    "genre": "스릴러",
    "type": "현대소설",
    "origin": "없음",
    "era": "90년대",
    "rating": "전체관람가",
    "cost": 500,
    "profit_America": 482,
    "profit_world": 482,
    "rotten_tomato": 80,
    "IMDB_score": 7.7,
    "IMDB_number": 74136
  },
  {
    "title": "The General's Daughter",
    "genre": "드라마",
    "type": "현대소설",
    "origin": "책",
    "era": "90년대",
    "rating": "전체관람가",
    "cost": 600,
    "profit_America": 1027,
    "profit_world": 1497,
    "rotten_tomato": 22,
    "IMDB_score": 6.1,
    "IMDB_number": 23570
  },
  {
    "title": "Garden State",
    "genre": "드라마",
    "type": "현대소설",
    "origin": "없음",
    "era": "2000년대",
    "rating": "전체관람가",
    "cost": 25,
    "profit_America": 267,
    "profit_world": 323,
    "rotten_tomato": 86,
    "IMDB_score": 7.9,
    "IMDB_number": 92594
  },
  {
    "title": "How the Grinch Stole Christmas",
    "genre": "코미디",
    "type": "아동소설",
    "origin": "책",
    "era": "2000년대",
    "rating": "7세이상",
    "cost": 1230,
    "profit_America": 2600,
    "profit_world": 3451,
    "rotten_tomato": 53,
    "IMDB_score": 5.7,
    "IMDB_number": 40310
  },
  {
    "title": "The Happening",
    "genre": "스릴러",
    "type": "공상과학",
    "origin": "없음",
    "era": "2000년대",
    "rating": "전체관람가",
    "cost": 600,
    "profit_America": 645,
    "profit_world": 1634,
    "rotten_tomato": 18,
    "IMDB_score": 5.2,
    "IMDB_number": 72259
  },
  {
    "title": "Heist",
    "genre": "액션",
    "type": "현대소설",
    "origin": "없음",
    "era": "2000년대",
    "rating": "전체관람가",
    "cost": 350,
    "profit_America": 234,
    "profit_world": 284,
    "rotten_tomato": 66,
    "IMDB_score": 3.2,
    "IMDB_number": 77
  },
  {
    "title": "The Haunting",
    "genre": "호러",
    "type": "현대소설",
    "origin": "책",
    "era": "90년대",
    "rating": "15세이상",
    "cost": 800,
    "profit_America": 911,
    "profit_world": 1801,
    "rotten_tomato": 17,
    "IMDB_score": 4.6,
    "IMDB_number": 31808
  },
  {
    "title": "The Hills Have Eyes",
    "genre": "호러",
    "type": "현대소설",
    "origin": "영화",
    "era": "2000년대",
    "rating": "전체관람가",
    "cost": 170,
    "profit_America": 417,
    "profit_world": 696,
    "rotten_tomato": 49,
    "IMDB_score": 6.5,
    "IMDB_number": 43747
  },
  {
    "title": "Holes",
    "genre": "드라마",
    "type": "현대소설",
    "origin": "책",
    "era": "2000년대",
    "rating": "7세이상",
    "cost": 200,
    "profit_America": 673,
    "profit_world": 723,
    "rotten_tomato": 77,
    "IMDB_score": 7.1,
    "IMDB_number": 19388
  },
  {
    "title": "Hollow Man",
    "genre": "호러",
    "type": "공상과학",
    "origin": "없음",
    "era": "2000년대",
    "rating": "전체관람가",
    "cost": 900,
    "profit_America": 732,
    "profit_world": 1912,
    "rotten_tomato": 28,
    "IMDB_score": 5.5,
    "IMDB_number": 41499
  },
  {
    "title": "Harry Potter and the Chamber of Secrets",
    "genre": "어드벤처",
    "type": "판타지",
    "origin": "책",
    "era": "2000년대",
    "rating": "7세이상",
    "cost": 1000,
    "profit_America": 2619,
    "profit_world": 8789,
    "rotten_tomato": 82,
    "IMDB_score": 7.2,
    "IMDB_number": 120063
  },
  {
    "title": "Inkheart",
    "genre": "어드벤처",
    "type": "판타지",
    "origin": "책",
    "era": "2000년대",
    "rating": "7세이상",
    "cost": 600,
    "profit_America": 173,
    "profit_world": 580,
    "rotten_tomato": 40,
    "IMDB_score": 6.1,
    "IMDB_number": 14157
  },
  {
    "title": "In & Out",
    "genre": "코미디",
    "type": "현대소설",
    "origin": "없음",
    "era": "90년대",
    "rating": "15세이상",
    "cost": 350,
    "profit_America": 638,
    "profit_world": 832,
    "rotten_tomato": 71,
    "IMDB_score": 6.1,
    "IMDB_number": 18773
  },
  {
    "title": "The Insider",
    "genre": "드라마",
    "type": "각색",
    "origin": "책",
    "era": "90년대",
    "rating": "전체관람가",
    "cost": 680,
    "profit_America": 289,
    "profit_world": 602,
    "rotten_tomato": 96,
    "IMDB_score": 8,
    "IMDB_number": 68747
  },
  {
    "title": "Iron Man",
    "genre": "액션",
    "type": "영웅물",
    "origin": "만화",
    "era": "2000년대",
    "rating": "15세이상",
    "cost": 1860,
    "profit_America": 3186,
    "profit_world": 5826,
    "rotten_tomato": 94,
    "IMDB_score": 7.9,
    "IMDB_number": 174040
  },
  {
    "title": "Die Another Day",
    "genre": "액션",
    "type": "현대소설",
    "origin": "책",
    "era": "2000년대",
    "rating": "15세이상",
    "cost": 1420,
    "profit_America": 1609,
    "profit_world": 4319,
    "rotten_tomato": 59,
    "IMDB_score": 6,
    "IMDB_number": 67476
  },
  {
    "title": "Casino Royale",
    "genre": "액션",
    "type": "현대소설",
    "origin": "책",
    "era": "2000년대",
    "rating": "15세이상",
    "cost": 1020,
    "profit_America": 1673,
    "profit_world": 5963,
    "rotten_tomato": 94,
    "IMDB_score": 8,
    "IMDB_number": 172936
  },
  {
    "title": "Quantum of Solace",
    "genre": "액션",
    "type": "현대소설",
    "origin": "책",
    "era": "2000년대",
    "rating": "15세이상",
    "cost": 2300,
    "profit_America": 1693,
    "profit_world": 5763,
    "rotten_tomato": 64,
    "IMDB_score": 6.8,
    "IMDB_number": 93596
  },
  {
    "title": "Julie & Julia",
    "genre": "코미디",
    "type": "현대소설",
    "origin": "책",
    "era": "2000년대",
    "rating": "15세이상",
    "cost": 400,
    "profit_America": 941,
    "profit_world": 1266,
    "rotten_tomato": 75,
    "IMDB_score": 7.2,
    "IMDB_number": 22269
  },
  {
    "title": "Kiss of the Dragon",
    "genre": "액션",
    "type": "현대소설",
    "origin": "없음",
    "era": "2000년대",
    "rating": "전체관람가",
    "cost": 250,
    "profit_America": 368,
    "profit_world": 368,
    "rotten_tomato": 51,
    "IMDB_score": 6.3,
    "IMDB_number": 22087
  },
  {
    "title": "Kill Bill: Volume 1",
    "genre": "액션",
    "type": "현대소설",
    "origin": "없음",
    "era": "2000년대",
    "rating": "전체관람가",
    "cost": 550,
    "profit_America": 700,
    "profit_world": 1800,
    "rotten_tomato": 85,
    "IMDB_score": 8.2,
    "IMDB_number": 231761
  },
  {
    "title": "Kingdom of Heaven",
    "genre": "어드벤처",
    "type": "역사소설",
    "origin": "없음",
    "era": "2000년대",
    "rating": "전체관람가",
    "cost": 1100,
    "profit_America": 473,
    "profit_world": 2113,
    "rotten_tomato": 39,
    "IMDB_score": 7.1,
    "IMDB_number": 83189
  },
  {
    "title": "Knowing",
    "genre": "스릴러",
    "type": "현대소설",
    "origin": "책",
    "era": "2000년대",
    "rating": "15세이상",
    "cost": 500,
    "profit_America": 799,
    "profit_world": 1878,
    "rotten_tomato": 32,
    "IMDB_score": 6.4,
    "IMDB_number": 58138
  },
  {
    "title": "K-PAX",
    "genre": "드라마",
    "type": "공상과학",
    "origin": "책",
    "era": "2000년대",
    "rating": "15세이상",
    "cost": 480,
    "profit_America": 503,
    "profit_world": 503,
    "rotten_tomato": 40,
    "IMDB_score": 7.3,
    "IMDB_number": 50475
  },
  {
    "title": "King's Ransom",
    "genre": "코미디",
    "type": "현대소설",
    "origin": "없음",
    "era": "2000년대",
    "rating": "15세이상",
    "cost": 250,
    "profit_America": 40,
    "profit_world": 40,
    "rotten_tomato": 2,
    "IMDB_score": 3.5,
    "IMDB_number": 2251
  },
  {
    "title": "Kundun",
    "genre": "드라마",
    "type": "각색",
    "origin": "없음",
    "era": "90년대",
    "rating": "15세이상",
    "cost": 280,
    "profit_America": 56,
    "profit_world": 56,
    "rotten_tomato": 76,
    "IMDB_score": 7,
    "IMDB_number": 10248
  },
  {
    "title": "Ladder 49",
    "genre": "액션",
    "type": "현대소설",
    "origin": "없음",
    "era": "2000년대",
    "rating": "15세이상",
    "cost": 600,
    "profit_America": 745,
    "profit_world": 1023,
    "rotten_tomato": 40,
    "IMDB_score": 6.5,
    "IMDB_number": 23369
  },
  {
    "title": "The Life Aquatic with Steve Zissou",
    "genre": "코미디",
    "type": "현대소설",
    "origin": "없음",
    "era": "2000년대",
    "rating": "전체관람가",
    "cost": 500,
    "profit_America": 240,
    "profit_world": 348,
    "rotten_tomato": 53,
    "IMDB_score": 7.2,
    "IMDB_number": 57889
  },
  {
    "title": "Like Mike",
    "genre": "코미디",
    "type": "아동소설",
    "origin": "없음",
    "era": "2000년대",
    "rating": "7세이상",
    "cost": 300,
    "profit_America": 514,
    "profit_world": 624,
    "rotten_tomato": 56,
    "IMDB_score": 4.4,
    "IMDB_number": 4870
  },
  {
    "title": "Lord of War",
    "genre": "액션",
    "type": "현대소설",
    "origin": "없음",
    "era": "2000년대",
    "rating": "전체관람가",
    "cost": 420,
    "profit_America": 241,
    "profit_world": 621,
    "rotten_tomato": 61,
    "IMDB_score": 7.7,
    "IMDB_number": 80124
  },
  {
    "title": "The Last Samurai",
    "genre": "액션",
    "type": "역사소설",
    "origin": "없음",
    "era": "2000년대",
    "rating": "전체관람가",
    "cost": 1200,
    "profit_America": 1111,
    "profit_world": 4568,
    "rotten_tomato": 65,
    "IMDB_score": 7.8,
    "IMDB_number": 106002
  },
  {
    "title": "Mad City",
    "genre": "드라마",
    "type": "현대소설",
    "origin": "없음",
    "era": "90년대",
    "rating": "15세이상",
    "cost": 500,
    "profit_America": 105,
    "profit_world": 105,
    "rotten_tomato": 37,
    "IMDB_score": 6.1,
    "IMDB_number": 9611
  },
  {
    "title": "Paul Blart: Mall Cop",
    "genre": "코미디",
    "type": "현대소설",
    "origin": "없음",
    "era": "2000년대",
    "rating": "7세이상",
    "cost": 260,
    "profit_America": 1463,
    "profit_world": 1804,
    "rotten_tomato": 35,
    "IMDB_score": 5.3,
    "IMDB_number": 23753
  },
  {
    "title": "Marci X",
    "genre": "코미디",
    "type": "현대소설",
    "origin": "없음",
    "era": "2000년대",
    "rating": "전체관람가",
    "cost": 200,
    "profit_America": 16,
    "profit_world": 16,
    "rotten_tomato": 10,
    "IMDB_score": 2.4,
    "IMDB_number": 3449
  },
  {
    "title": "Meet Joe Black",
    "genre": "드라마",
    "type": "판타지",
    "origin": "없음",
    "era": "90년대",
    "rating": "15세이상",
    "cost": 850,
    "profit_America": 446,
    "profit_world": 446,
    "rotten_tomato": 50,
    "IMDB_score": 6.9,
    "IMDB_number": 56067
  },
  {
    "title": "Mindhunters",
    "genre": "스릴러",
    "type": "현대소설",
    "origin": "없음",
    "era": "2000년대",
    "rating": "전체관람가",
    "cost": 270,
    "profit_America": 44,
    "profit_world": 165,
    "rotten_tomato": 26,
    "IMDB_score": 6.2,
    "IMDB_number": 23357
  },
  {
    "title": "Captain Corelli's Mandolin",
    "genre": "드라마",
    "type": "역사소설",
    "origin": "책",
    "era": "2000년대",
    "rating": "전체관람가",
    "cost": 570,
    "profit_America": 255,
    "profit_world": 620,
    "rotten_tomato": 29,
    "IMDB_score": 5.7,
    "IMDB_number": 14706
  },
  {
    "title": "Moonlight Mile",
    "genre": "드라마",
    "type": "현대소설",
    "origin": "없음",
    "era": "2000년대",
    "rating": "15세이상",
    "cost": 210,
    "profit_America": 68,
    "profit_world": 68,
    "rotten_tomato": 62,
    "IMDB_score": 6.7,
    "IMDB_number": 8346
  },
  {
    "title": "Me and Orson Welles",
    "genre": "드라마",
    "type": "역사소설",
    "origin": "책",
    "era": "2000년대",
    "rating": "15세이상",
    "cost": 250,
    "profit_America": 11,
    "profit_world": 11,
    "rotten_tomato": 84,
    "IMDB_score": 7.1,
    "IMDB_number": 2417
  },
  {
    "title": "Meet the Spartans",
    "genre": "코미디",
    "type": "역사소설",
    "origin": "없음",
    "era": "2000년대",
    "rating": "15세이상",
    "cost": 300,
    "profit_America": 382,
    "profit_world": 846,
    "rotten_tomato": 2,
    "IMDB_score": 2.4,
    "IMDB_number": 47281
  },
  {
    "title": "The Matrix Reloaded",
    "genre": "액션",
    "type": "공상과학",
    "origin": "없음",
    "era": "2000년대",
    "rating": "전체관람가",
    "cost": 1270,
    "profit_America": 2815,
    "profit_world": 7385,
    "rotten_tomato": 73,
    "IMDB_score": 7.1,
    "IMDB_number": 148874
  },
  {
    "title": "Murder by Numbers",
    "genre": "스릴러",
    "type": "현대소설",
    "origin": "없음",
    "era": "2000년대",
    "rating": "전체관람가",
    "cost": 500,
    "profit_America": 318,
    "profit_world": 566,
    "rotten_tomato": 31,
    "IMDB_score": 5.9,
    "IMDB_number": 22318
  },
  {
    "title": "The Muse",
    "genre": "코미디",
    "type": "현대소설",
    "origin": "없음",
    "era": "90년대",
    "rating": "15세이상",
    "cost": 150,
    "profit_America": 116,
    "profit_world": 116,
    "rotten_tomato": 51,
    "IMDB_score": 5.5,
    "IMDB_number": 6507
  },
  {
    "title": "Night at the Museum",
    "genre": "코미디",
    "type": "판타지",
    "origin": "책",
    "era": "2000년대",
    "rating": "7세이상",
    "cost": 1100,
    "profit_America": 2508,
    "profit_world": 5744,
    "rotten_tomato": 43,
    "IMDB_score": 6.4,
    "IMDB_number": 67133
  },
  {
    "title": "Monsters vs. Aliens",
    "genre": "어드벤처",
    "type": "판타지",
    "origin": "만화",
    "era": "2000년대",
    "rating": "7세이상",
    "cost": 1750,
    "profit_America": 1983,
    "profit_world": 3816,
    "rotten_tomato": 72,
    "IMDB_score": 6.8,
    "IMDB_number": 26582
  },
  {
    "title": "A Mighty Wind",
    "genre": "코미디",
    "type": "현대소설",
    "origin": "없음",
    "era": "2000년대",
    "rating": "15세이상",
    "cost": 60,
    "profit_America": 175,
    "profit_world": 185,
    "rotten_tomato": 88,
    "IMDB_score": 7.2,
    "IMDB_number": 13602
  },
  {
    "title": "My Dog Skip",
    "genre": "드라마",
    "type": "아동소설",
    "origin": "없음",
    "era": "2000년대",
    "rating": "7세이상",
    "cost": 70,
    "profit_America": 340,
    "profit_world": 355,
    "rotten_tomato": 72,
    "IMDB_score": 6.9,
    "IMDB_number": 9029
  },
  {
    "title": "My Fellow Americans",
    "genre": "코미디",
    "type": "현대소설",
    "origin": "없음",
    "era": "90년대",
    "rating": "15세이상",
    "cost": 215,
    "profit_America": 223,
    "profit_world": 223,
    "rotten_tomato": 50,
    "IMDB_score": 6.3,
    "IMDB_number": 6366
  },
  {
    "title": "The Nativity Story",
    "genre": "드라마",
    "type": "각색",
    "origin": "책",
    "era": "2000년대",
    "rating": "7세이상",
    "cost": 350,
    "profit_America": 376,
    "profit_world": 464,
    "rotten_tomato": 37,
    "IMDB_score": 6.6,
    "IMDB_number": 4701
  },
  {
    "title": "In Good Company",
    "genre": "코미디",
    "type": "현대소설",
    "origin": "없음",
    "era": "2000년대",
    "rating": "15세이상",
    "cost": 260,
    "profit_America": 454,
    "profit_world": 634,
    "rotten_tomato": 84,
    "IMDB_score": 6.8,
    "IMDB_number": 25695
  },
  {
    "title": "Lucky Numbers",
    "genre": "코미디",
    "type": "현대소설",
    "origin": "없음",
    "era": "2000년대",
    "rating": "전체관람가",
    "cost": 650,
    "profit_America": 100,
    "profit_world": 100,
    "rotten_tomato": 23,
    "IMDB_score": 4.9,
    "IMDB_number": 5461
  },
  {
    "title": "The Interpreter",
    "genre": "스릴러",
    "type": "현대소설",
    "origin": "없음",
    "era": "2000년대",
    "rating": "15세이상",
    "cost": 900,
    "profit_America": 727,
    "profit_world": 1639,
    "rotten_tomato": 58,
    "IMDB_score": 6.5,
    "IMDB_number": 38227
  },
  {
    "title": "The Number 23",
    "genre": "스릴러",
    "type": "현대소설",
    "origin": "없음",
    "era": "2000년대",
    "rating": "전체관람가",
    "cost": 320,
    "profit_America": 351,
    "profit_world": 765,
    "rotten_tomato": 8,
    "IMDB_score": 6.2,
    "IMDB_number": 59174
  },
  {
    "title": "The New World",
    "genre": "어드벤처",
    "type": "역사소설",
    "origin": "없음",
    "era": "2000년대",
    "rating": "15세이상",
    "cost": 300,
    "profit_America": 127,
    "profit_world": 261,
    "rotten_tomato": 60,
    "IMDB_score": 6.9,
    "IMDB_number": 33248
  },
  {
    "title": "Ocean's Eleven",
    "genre": "코미디",
    "type": "현대소설",
    "origin": "영화",
    "era": "2000년대",
    "rating": "15세이상",
    "cost": 1100,
    "profit_America": 1834,
    "profit_world": 4507,
    "rotten_tomato": 81,
    "IMDB_score": 7.6,
    "IMDB_number": 139034
  },
  {
    "title": "Old School",
    "genre": "코미디",
    "type": "현대소설",
    "origin": "없음",
    "era": "2000년대",
    "rating": "전체관람가",
    "cost": 240,
    "profit_America": 751,
    "profit_world": 863,
    "rotten_tomato": 60,
    "IMDB_score": 7,
    "IMDB_number": 60477
  },
  {
    "title": "Out of Time",
    "genre": "스릴러",
    "type": "현대소설",
    "origin": "없음",
    "era": "2000년대",
    "rating": "15세이상",
    "cost": 500,
    "profit_America": 410,
    "profit_world": 554,
    "rotten_tomato": 65,
    "IMDB_score": 4.9,
    "IMDB_number": 151
  },
  {
    "title": "The Passion of the Christ",
    "genre": "드라마",
    "type": "각색",
    "origin": "책",
    "era": "2000년대",
    "rating": "전체관람가",
    "cost": 250,
    "profit_America": 3707,
    "profit_world": 6118,
    "rotten_tomato": 50,
    "IMDB_score": 7.1,
    "IMDB_number": 87326
  },
  {
    "title": "A Perfect Getaway",
    "genre": "스릴러",
    "type": "현대소설",
    "origin": "없음",
    "era": "2000년대",
    "rating": "전체관람가",
    "cost": 140,
    "profit_America": 155,
    "profit_world": 206,
    "rotten_tomato": 60,
    "IMDB_score": 6.5,
    "IMDB_number": 16324
  },
  {
    "title": "The Chronicles of Riddick",
    "genre": "어드벤처",
    "type": "공상과학",
    "origin": "없음",
    "era": "2000년대",
    "rating": "15세이상",
    "cost": 1200,
    "profit_America": 577,
    "profit_world": 1072,
    "rotten_tomato": 29,
    "IMDB_score": 6.4,
    "IMDB_number": 49383
  },
  {
    "title": "Planet of the Apes",
    "genre": "어드벤처",
    "type": "공상과학",
    "origin": "영화",
    "era": "2000년대",
    "rating": "15세이상",
    "cost": 1000,
    "profit_America": 1800,
    "profit_world": 3622,
    "rotten_tomato": 44,
    "IMDB_score": 5.5,
    "IMDB_number": 72763
  },
  {
    "title": "Possession",
    "genre": "드라마",
    "type": "현대소설",
    "origin": "책",
    "era": "2000년대",
    "rating": "15세이상",
    "cost": 250,
    "profit_America": 101,
    "profit_world": 148,
    "rotten_tomato": 64,
    "IMDB_score": 6.4,
    "IMDB_number": 6789
  },
  {
    "title": "Practical Magic",
    "genre": "코미디",
    "type": "판타지",
    "origin": "책",
    "era": "90년대",
    "rating": "15세이상",
    "cost": 600,
    "profit_America": 468,
    "profit_world": 683,
    "rotten_tomato": 21,
    "IMDB_score": 5.5,
    "IMDB_number": 20196
  },
  {
    "title": "Quarantine",
    "genre": "호러",
    "type": "현대소설",
    "origin": "없음",
    "era": "2000년대",
    "rating": "전체관람가",
    "cost": 120,
    "profit_America": 316,
    "profit_world": 360,
    "rotten_tomato": 58,
    "IMDB_score": 6.1,
    "IMDB_number": 21939
  },
  {
    "title": "Rabbit-Proof Fence",
    "genre": "드라마",
    "type": "역사소설",
    "origin": "책",
    "era": "2000년대",
    "rating": "7세이상",
    "cost": 70,
    "profit_America": 61,
    "profit_world": 161,
    "rotten_tomato": 87,
    "IMDB_score": 7.6,
    "IMDB_number": 13241
  },
  {
    "title": "Ratatouille",
    "genre": "코미디",
    "type": "판타지",
    "origin": "없음",
    "era": "2000년대",
    "rating": "19세이상",
    "cost": 1500,
    "profit_America": 2064,
    "profit_world": 6204,
    "rotten_tomato": 96,
    "IMDB_score": 8.1,
    "IMDB_number": 131929
  },
  {
    "title": "Robots",
    "genre": "어드벤처",
    "type": "아동소설",
    "origin": "없음",
    "era": "2000년대",
    "rating": "7세이상",
    "cost": 800,
    "profit_America": 1282,
    "profit_world": 2607,
    "rotten_tomato": 64,
    "IMDB_score": 6.4,
    "IMDB_number": 27361
  },
  {
    "title": "Red Dragon",
    "genre": "스릴러",
    "type": "현대소설",
    "origin": "책",
    "era": "2000년대",
    "rating": "전체관람가",
    "cost": 780,
    "profit_America": 929,
    "profit_world": 2064,
    "rotten_tomato": 68,
    "IMDB_score": 7.3,
    "IMDB_number": 66386
  },
  {
    "title": "The Reader",
    "genre": "드라마",
    "type": "현대소설",
    "origin": "책",
    "era": "2000년대",
    "rating": "전체관람가",
    "cost": 330,
    "profit_America": 341,
    "profit_world": 1061,
    "rotten_tomato": 61,
    "IMDB_score": 7.7,
    "IMDB_number": 46984
  },
  {
    "title": "The Rocker",
    "genre": "코미디",
    "type": "현대소설",
    "origin": "없음",
    "era": "2000년대",
    "rating": "15세이상",
    "cost": 150,
    "profit_America": 64,
    "profit_world": 87,
    "rotten_tomato": 40,
    "IMDB_score": 6.3,
    "IMDB_number": 11859
  },
  {
    "title": "Rock Star",
    "genre": "드라마",
    "type": "현대소설",
    "origin": "없음",
    "era": "2000년대",
    "rating": "전체관람가",
    "cost": 380,
    "profit_America": 169,
    "profit_world": 193,
    "rotten_tomato": 52,
    "IMDB_score": 5.8,
    "IMDB_number": 15806
  },
  {
    "title": "Romeo Must Die",
    "genre": "액션",
    "type": "현대소설",
    "origin": "없음",
    "era": "2000년대",
    "rating": "전체관람가",
    "cost": 250,
    "profit_America": 559,
    "profit_world": 910,
    "rotten_tomato": 33,
    "IMDB_score": 5.9,
    "IMDB_number": 25309
  },
  {
    "title": "Road Trip",
    "genre": "코미디",
    "type": "현대소설",
    "origin": "없음",
    "era": "2000년대",
    "rating": "전체관람가",
    "cost": 160,
    "profit_America": 685,
    "profit_world": 1197,
    "rotten_tomato": 59,
    "IMDB_score": 6.4,
    "IMDB_number": 44702
  },
  {
    "title": "Rules of Engagement",
    "genre": "스릴러",
    "type": "현대소설",
    "origin": "책",
    "era": "2000년대",
    "rating": "전체관람가",
    "cost": 600,
    "profit_America": 613,
    "profit_world": 717,
    "rotten_tomato": 37,
    "IMDB_score": 6.2,
    "IMDB_number": 18462
  },
  {
    "title": "Rush Hour 2",
    "genre": "액션",
    "type": "현대소설",
    "origin": "없음",
    "era": "2000년대",
    "rating": "15세이상",
    "cost": 900,
    "profit_America": 2261,
    "profit_world": 3474,
    "rotten_tomato": 51,
    "IMDB_score": 6.4,
    "IMDB_number": 52049
  },
  {
    "title": "Saw VI",
    "genre": "호러",
    "type": "현대소설",
    "origin": "없음",
    "era": "2000년대",
    "rating": "전체관람가",
    "cost": 110,
    "profit_America": 276,
    "profit_world": 612,
    "rotten_tomato": 42,
    "IMDB_score": 6.2,
    "IMDB_number": 18091
  },
  {
    "title": "About Schmidt",
    "genre": "드라마",
    "type": "현대소설",
    "origin": "책",
    "era": "2000년대",
    "rating": "전체관람가",
    "cost": 300,
    "profit_America": 650,
    "profit_world": 1058,
    "rotten_tomato": 85,
    "IMDB_score": 7.3,
    "IMDB_number": 53760
  },
  {
    "title": "Shutter Island",
    "genre": "스릴러",
    "type": "역사소설",
    "origin": "책",
    "era": "2000년대",
    "rating": "전체관람가",
    "cost": 800,
    "profit_America": 1280,
    "profit_world": 2945,
    "rotten_tomato": 67,
    "IMDB_score": 8,
    "IMDB_number": 105706
  },
  {
    "title": "Shrek",
    "genre": "어드벤처",
    "type": "아동소설",
    "origin": "책",
    "era": "2000년대",
    "rating": "7세이상",
    "cost": 500,
    "profit_America": 2676,
    "profit_world": 4843,
    "rotten_tomato": 89,
    "IMDB_score": 8,
    "IMDB_number": 163855
  },
  {
    "title": "Shrek 2",
    "genre": "어드벤처",
    "type": "아동소설",
    "origin": "책",
    "era": "2000년대",
    "rating": "7세이상",
    "cost": 700,
    "profit_America": 4412,
    "profit_world": 9198,
    "rotten_tomato": 89,
    "IMDB_score": 7.5,
    "IMDB_number": 95658
  },
  {
    "title": "The Sixth Sense",
    "genre": "스릴러",
    "type": "현대소설",
    "origin": "없음",
    "era": "90년대",
    "rating": "15세이상",
    "cost": 400,
    "profit_America": 2935,
    "profit_world": 6728,
    "rotten_tomato": 85,
    "IMDB_score": 8.2,
    "IMDB_number": 238745
  },
  {
    "title": "The Skeleton Key",
    "genre": "호러",
    "type": "현대소설",
    "origin": "없음",
    "era": "2000년대",
    "rating": "15세이상",
    "cost": 400,
    "profit_America": 479,
    "profit_world": 929,
    "rotten_tomato": 38,
    "IMDB_score": 6.5,
    "IMDB_number": 29810
  },
  {
    "title": "Sleepy Hollow",
    "genre": "호러",
    "type": "역사소설",
    "origin": "책",
    "era": "90년대",
    "rating": "전체관람가",
    "cost": 700,
    "profit_America": 1010,
    "profit_world": 2070,
    "rotten_tomato": 68,
    "IMDB_score": 7.5,
    "IMDB_number": 107511
  },
  {
    "title": "Superbad",
    "genre": "코미디",
    "type": "현대소설",
    "origin": "없음",
    "era": "2000년대",
    "rating": "전체관람가",
    "cost": 175,
    "profit_America": 1214,
    "profit_world": 1698,
    "rotten_tomato": 87,
    "IMDB_score": 7.8,
    "IMDB_number": 134212
  },
  {
    "title": "Superman Returns",
    "genre": "어드벤처",
    "type": "영웅물",
    "origin": "만화",
    "era": "2000년대",
    "rating": "15세이상",
    "cost": 2320,
    "profit_America": 2001,
    "profit_world": 3911,
    "rotten_tomato": 76,
    "IMDB_score": 6.6,
    "IMDB_number": 102751
  },
  {
    "title": "Small Time Crooks",
    "genre": "코미디",
    "type": "현대소설",
    "origin": "없음",
    "era": "2000년대",
    "rating": "7세이상",
    "cost": 180,
    "profit_America": 172,
    "profit_world": 299,
    "rotten_tomato": 66,
    "IMDB_score": 6.5,
    "IMDB_number": 15636
  },
  {
    "title": "Stepmom",
    "genre": "드라마",
    "type": "현대소설",
    "origin": "없음",
    "era": "90년대",
    "rating": "15세이상",
    "cost": 500,
    "profit_America": 911,
    "profit_world": 1197,
    "rotten_tomato": 43,
    "IMDB_score": 6.2,
    "IMDB_number": 18505
  },
  {
    "title": "The Perfect Storm",
    "genre": "드라마",
    "type": "각색",
    "origin": "책",
    "era": "2000년대",
    "rating": "15세이상",
    "cost": 1200,
    "profit_America": 1826,
    "profit_world": 3287,
    "rotten_tomato": 47,
    "IMDB_score": 6.2,
    "IMDB_number": 55716
  },
  {
    "title": "Tadpole",
    "genre": "코미디",
    "type": "현대소설",
    "origin": "없음",
    "era": "2000년대",
    "rating": "15세이상",
    "cost": 1,
    "profit_America": 28,
    "profit_world": 32,
    "rotten_tomato": 78,
    "IMDB_score": 6.1,
    "IMDB_number": 3800
  },
  {
    "title": "The Tale of Despereaux",
    "genre": "어드벤처",
    "type": "아동소설",
    "origin": "책",
    "era": "2000년대",
    "rating": "19세이상",
    "cost": 600,
    "profit_America": 508,
    "profit_world": 887,
    "rotten_tomato": 55,
    "IMDB_score": 6.1,
    "IMDB_number": 7460
  },
  {
    "title": "Tears of the Sun",
    "genre": "액션",
    "type": "현대소설",
    "origin": "없음",
    "era": "2000년대",
    "rating": "전체관람가",
    "cost": 750,
    "profit_America": 436,
    "profit_world": 856,
    "rotten_tomato": 34,
    "IMDB_score": 6.4,
    "IMDB_number": 34304
  },
  {
    "title": "The Box",
    "genre": "스릴러",
    "type": "판타지",
    "origin": "책",
    "era": "2000년대",
    "rating": "15세이상",
    "cost": 250,
    "profit_America": 150,
    "profit_world": 263,
    "rotten_tomato": 45,
    "IMDB_score": 6.8,
    "IMDB_number": 418
  },
  {
    "title": "The League of Extraordinary Gentlemen",
    "genre": "어드벤처",
    "type": "영웅물",
    "origin": "만화",
    "era": "2000년대",
    "rating": "15세이상",
    "cost": 780,
    "profit_America": 664,
    "profit_world": 1792,
    "rotten_tomato": 17,
    "IMDB_score": 5.5,
    "IMDB_number": 50710
  },
  {
    "title": "The Mist",
    "genre": "호러",
    "type": "공상과학",
    "origin": "책",
    "era": "2000년대",
    "rating": "전체관람가",
    "cost": 130,
    "profit_America": 255,
    "profit_world": 547,
    "rotten_tomato": 73,
    "IMDB_score": 7.4,
    "IMDB_number": 76830
  },
  {
    "title": "Tomorrow Never Dies",
    "genre": "액션",
    "type": "현대소설",
    "origin": "책",
    "era": "90년대",
    "rating": "15세이상",
    "cost": 1100,
    "profit_America": 1253,
    "profit_world": 3395,
    "rotten_tomato": 55,
    "IMDB_score": 6.4,
    "IMDB_number": 46650
  },
  {
    "title": "The Town",
    "genre": "드라마",
    "type": "현대소설",
    "origin": "책",
    "era": "2000년대",
    "rating": "전체관람가",
    "cost": 370,
    "profit_America": 309,
    "profit_world": 331,
    "rotten_tomato": 84,
    "IMDB_score": 8.7,
    "IMDB_number": 493
  }
];